version: "3.7"
services:
  web:
    build: .
    ports:
      - "8000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
    networks:
      - mynetwork
      
  postgres:
    image: "postgres"
    restart: always
    ports: 
     - "5432:5432"
    environment: 
     - POSTGRES_USER=admin
     - POSTGRES_PASSWORD=admin
     - POSTGRES_DB=postgres
    volumes:
     - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mynetwork
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports: 
      - 80:80
    depends_on:
      - postgres 

networks:
  mynetwork:
    driver: bridge
